/**
 * Copyright 2026 PLUMB contributors
 * SPDX-License-Identifier: Apache-2.0
 */

export interface FrozenProviderRow {
  readonly id: string;
  readonly ompId: string | null;
  readonly name: string;
  readonly category:
    | 'coding_plan'
    | 'oauth_account'
    | 'api_key'
    | 'local'
    | 'custom_endpoint';
  readonly group: string | undefined;
  readonly order: number | undefined;
  readonly selectable: boolean;
  readonly oauthPosture?:
    | 'PLUMB_OWNED_VALID_REGISTRATION'
    | 'OFFICIAL_PUBLIC_DEVICE_FLOW'
    | 'OFFICIAL_CLI_DELEGATION'
    | 'UPSTREAM_PRODUCT_OWNED_REGISTRATION'
    | 'MISSING_REGISTRATION'
    | 'PROVIDER_POLICY_BLOCKED';
  /** Phase A scope: only the verified reference routes have a derived
   *  final classification. The other rows remain `UNCLASSIFIED` and
   *  are filled in by later phases. */
  readonly finalClassification:
    | 'PRODUCTION_READY'
    | 'IMPLEMENTATION_COMPLETE_EXTERNAL_CREDENTIAL_REQUIRED'
    | 'BLOCKED_CLIENT_REGISTRATION'
    | 'BLOCKED_PROVIDER_POLICY'
    | 'IMPLEMENTATION_INCOMPLETE_NOT_SELECTABLE'
    | 'PARTIAL_NOT_SELECTABLE'
    | 'PROVIDER_HAS_NO_MODEL_ENUMERATION'
    | 'BUNDLED_CATALOG_ONLY'
    | 'LOCAL_RUNTIME_NOT_AVAILABLE'
    | 'INVALID_CONFIGURATION_NOT_SELECTABLE'
    | 'NOT_PRESENT_AT_PINNED_SHA'
    | 'UNCLASSIFIED';
}

export const REFERENCE_ROUTES: ReadonlySet<string> = new Set([
  'nvidia',
  'ollama',
  'lm-studio',
  'llama-cpp',
  'vllm',
  'custom-openai-compat',
]);

/**
 * Frozen provider rows. The set is hand-pinned to the verified reference
 * routes plus the catalog ids that must remain visible to the dialog. The
 * `selectable` flag mirrors the live `SELECTABLE_PROVIDERS` filtering today.
 * Future inventory updates land via separate commits, not by mutating this
 * file silently.
 */
export const PLUMB_INVENTORY_FIXTURE: ReadonlyArray<FrozenProviderRow> = [
  // ── Verified reference routes (must never be removed from this list) ──
  {
    id: 'nvidia',
    ompId: 'nvidia',
    name: 'NVIDIA',
    category: 'api_key',
    group: 'API Providers',
    order: 16,
    selectable: true,
    finalClassification: 'PRODUCTION_READY',
  },
  {
    id: 'ollama',
    ompId: 'ollama',
    name: 'Ollama',
    category: 'local',
    group: 'Local Models',
    order: 1,
    selectable: true,
    finalClassification: 'PRODUCTION_READY',
  },
  {
    id: 'lm-studio',
    ompId: 'lm-studio',
    name: 'LM Studio',
    category: 'local',
    group: 'Local Models',
    order: 3,
    selectable: true,
    finalClassification: 'PRODUCTION_READY',
  },
  {
    id: 'llama-cpp',
    ompId: 'llama.cpp',
    name: 'llama.cpp',
    category: 'local',
    group: 'Local Models',
    order: 4,
    selectable: true,
    finalClassification: 'PRODUCTION_READY',
  },
  {
    id: 'vllm',
    ompId: 'vllm',
    name: 'vLLM',
    category: 'local',
    group: 'Local Models',
    order: 5,
    selectable: true,
    finalClassification: 'PRODUCTION_READY',
  },
  {
    id: 'custom-openai-compat',
    ompId: null,
    name: 'Custom OpenAI-Compatible Endpoint',
    category: 'custom_endpoint',
    group: 'Custom',
    order: 1,
    selectable: true,
    finalClassification: 'PRODUCTION_READY',
  },

  // ── Coding plans (frozen for snapshot, classified by later phases) ──
  {
    id: 'openai-codex',
    ompId: 'openai-codex',
    name: 'ChatGPT Plus/Pro (Codex Subscription)',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 1,
    selectable: false,
    oauthPosture: 'UPSTREAM_PRODUCT_OWNED_REGISTRATION',
    finalClassification: 'BLOCKED_CLIENT_REGISTRATION',
  },
  {
    id: 'github-copilot',
    ompId: 'github-copilot',
    name: 'GitHub Copilot',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 2,
    selectable: true,
    oauthPosture: 'UPSTREAM_PRODUCT_OWNED_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'cursor',
    ompId: 'cursor',
    name: 'Cursor',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 3,
    selectable: true,
    oauthPosture: 'UPSTREAM_PRODUCT_OWNED_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'kimi-code',
    ompId: 'kimi-code',
    name: 'Kimi Code',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 4,
    selectable: true,
    oauthPosture: 'OFFICIAL_PUBLIC_DEVICE_FLOW',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'minimax-code',
    ompId: 'minimax-code',
    name: 'MiniMax Token Plan (International)',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 5,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'minimax-code-cn',
    ompId: 'minimax-code-cn',
    name: 'MiniMax Token Plan (China)',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 6,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'alibaba-coding-plan',
    ompId: 'alibaba-coding-plan',
    name: 'Alibaba Coding Plan',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 7,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'alibaba-token-plan',
    ompId: 'alibaba-token-plan',
    name: 'Alibaba Token Plan',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 8,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'zhipu-coding-plan',
    ompId: 'zhipu-coding-plan',
    name: 'Zhipu Coding Plan',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 9,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'qwen-portal',
    ompId: 'qwen-portal',
    name: 'Qwen Portal',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 10,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'zai-coding-plan',
    ompId: 'zai',
    name: 'Z.AI / GLM Coding Plan',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 11,
    selectable: true,
    oauthPosture: 'PLUMB_OWNED_VALID_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'firepass',
    ompId: 'firepass',
    name: 'Fire Pass',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 12,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'wafer-serverless',
    ompId: 'wafer-serverless',
    name: 'Wafer Serverless',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 13,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'xiaomi-token-plan-sgp',
    ompId: 'xiaomi-token-plan-sgp',
    name: 'Xiaomi Token Plan (SGP)',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 14,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'xiaomi-token-plan-ams',
    ompId: 'xiaomi-token-plan-ams',
    name: 'Xiaomi Token Plan (AMS)',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 15,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'xiaomi-token-plan-cn',
    ompId: 'xiaomi-token-plan-cn',
    name: 'Xiaomi Token Plan (CN)',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 16,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'umans',
    ompId: 'umans',
    name: 'Umans',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 17,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'sakana',
    ompId: 'sakana',
    name: 'Sakana',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 18,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'opencode-go',
    ompId: 'opencode-go',
    name: 'OpenCode Go',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 19,
    selectable: true,
    oauthPosture: 'UPSTREAM_PRODUCT_OWNED_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'opencode-zen',
    ompId: 'opencode-zen',
    name: 'OpenCode Zen',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 20,
    selectable: true,
    oauthPosture: 'UPSTREAM_PRODUCT_OWNED_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'devin',
    ompId: 'devin',
    name: 'Devin',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 21,
    selectable: true,
    oauthPosture: 'UPSTREAM_PRODUCT_OWNED_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'kilo',
    ompId: 'kilo',
    name: 'Kilo',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 22,
    selectable: true,
    oauthPosture: 'OFFICIAL_PUBLIC_DEVICE_FLOW',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'antigravity',
    ompId: 'google-antigravity',
    name: 'Antigravity (Google Cloud)',
    category: 'coding_plan',
    group: 'Coding Plans',
    order: 23,
    selectable: true,
    oauthPosture: 'UPSTREAM_PRODUCT_OWNED_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'google-gemini-cli',
    ompId: 'google-gemini-cli',
    name: 'Google Cloud Code Assist',
    category: 'coding_plan',
    group: 'Google',
    order: 1,
    selectable: true,
    oauthPosture: 'UPSTREAM_PRODUCT_OWNED_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },

  // ── OAuth account providers ──
  {
    id: 'anthropic',
    ompId: 'anthropic',
    name: 'Anthropic (Claude Pro/Max)',
    category: 'oauth_account',
    group: 'OAuth Accounts',
    order: 1,
    selectable: true,
    oauthPosture: 'UPSTREAM_PRODUCT_OWNED_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'xai-oauth',
    ompId: 'xai-oauth',
    name: 'xAI Grok OAuth',
    category: 'oauth_account',
    group: 'OAuth Accounts',
    order: 2,
    selectable: true,
    oauthPosture: 'OFFICIAL_PUBLIC_DEVICE_FLOW',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'xiaomi',
    ompId: 'xiaomi',
    name: 'Xiaomi MiMo',
    category: 'oauth_account',
    group: 'OAuth Accounts',
    order: 3,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'perplexity',
    ompId: 'perplexity',
    name: 'Perplexity',
    category: 'oauth_account',
    group: 'OAuth Accounts',
    order: 4,
    selectable: true,
    oauthPosture: 'MISSING_REGISTRATION',
    finalClassification: 'UNCLASSIFIED',
  },

  // ── API key providers ──
  {
    id: 'openai',
    ompId: 'openai',
    name: 'OpenAI',
    category: 'api_key',
    group: 'API Providers',
    order: 1,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'anthropic-api',
    ompId: 'anthropic',
    name: 'Anthropic API Key',
    category: 'api_key',
    group: 'API Providers',
    order: 2,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'google',
    ompId: 'google',
    name: 'Google Gemini',
    category: 'api_key',
    group: 'API Providers',
    order: 3,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'google-vertex',
    ompId: 'google-vertex',
    name: 'Google Vertex AI',
    category: 'api_key',
    group: 'API Providers',
    order: 4,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'xai',
    ompId: 'xai',
    name: 'xAI API',
    category: 'api_key',
    group: 'API Providers',
    order: 5,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'deepseek',
    ompId: 'deepseek',
    name: 'DeepSeek',
    category: 'api_key',
    group: 'API Providers',
    order: 6,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'mistral',
    ompId: 'mistral',
    name: 'Mistral',
    category: 'api_key',
    group: 'API Providers',
    order: 7,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'groq',
    ompId: 'groq',
    name: 'Groq',
    category: 'api_key',
    group: 'API Providers',
    order: 8,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'openrouter',
    ompId: 'openrouter',
    name: 'OpenRouter',
    category: 'api_key',
    group: 'API Providers',
    order: 9,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'fireworks',
    ompId: 'fireworks',
    name: 'Fireworks',
    category: 'api_key',
    group: 'API Providers',
    order: 10,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'together',
    ompId: 'together',
    name: 'Together',
    category: 'api_key',
    group: 'API Providers',
    order: 11,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'cerebras',
    ompId: 'cerebras',
    name: 'Cerebras',
    category: 'api_key',
    group: 'API Providers',
    order: 12,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'baseten',
    ompId: 'baseten',
    name: 'Baseten',
    category: 'api_key',
    group: 'API Providers',
    order: 13,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'novita',
    ompId: 'novita',
    name: 'Novita',
    category: 'api_key',
    group: 'API Providers',
    order: 14,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'huggingface',
    ompId: 'huggingface',
    name: 'Hugging Face',
    category: 'api_key',
    group: 'API Providers',
    order: 15,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'moonshot',
    ompId: 'moonshot',
    name: 'Moonshot',
    category: 'api_key',
    group: 'API Providers',
    order: 17,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'meta',
    ompId: 'meta',
    name: 'Meta',
    category: 'api_key',
    group: 'API Providers',
    order: 18,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'venice',
    ompId: 'venice',
    name: 'Venice',
    category: 'api_key',
    group: 'API Providers',
    order: 19,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'synthetic',
    ompId: 'synthetic',
    name: 'Synthetic',
    category: 'api_key',
    group: 'API Providers',
    order: 20,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'nanogpt',
    ompId: 'nanogpt',
    name: 'NanoGPT',
    category: 'api_key',
    group: 'API Providers',
    order: 21,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'azure',
    ompId: 'azure',
    name: 'Azure OpenAI',
    category: 'api_key',
    group: 'API Providers',
    order: 22,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'amazon-bedrock',
    ompId: 'amazon-bedrock',
    name: 'Amazon Bedrock',
    category: 'api_key',
    group: 'API Providers',
    order: 23,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'aimlapi',
    ompId: 'aimlapi',
    name: 'AIML API',
    category: 'api_key',
    group: 'API Providers',
    order: 24,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'siliconflow',
    ompId: 'siliconflow',
    name: 'SiliconFlow',
    category: 'api_key',
    group: 'API Providers',
    order: 25,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'siliconflow-cn',
    ompId: 'siliconflow-cn',
    name: 'SiliconFlow (CN)',
    category: 'api_key',
    group: 'API Providers',
    order: 26,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'qianfan',
    ompId: 'qianfan',
    name: 'Qianfan',
    category: 'api_key',
    group: 'API Providers',
    order: 27,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'coreweave',
    ompId: 'coreweave',
    name: 'CoreWeave',
    category: 'api_key',
    group: 'API Providers',
    order: 28,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'cloudflare-ai-gateway',
    ompId: 'cloudflare-ai-gateway',
    name: 'Cloudflare AI Gateway',
    category: 'api_key',
    group: 'API Providers',
    order: 29,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'vercel-ai-gateway',
    ompId: 'vercel-ai-gateway',
    name: 'Vercel AI Gateway',
    category: 'api_key',
    group: 'API Providers',
    order: 30,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'litellm',
    ompId: 'litellm',
    name: 'LiteLLM',
    category: 'api_key',
    group: 'API Providers',
    order: 31,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'zenmux',
    ompId: 'zenmux',
    name: 'ZenMux',
    category: 'api_key',
    group: 'API Providers',
    order: 32,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'minimax',
    ompId: 'minimax',
    name: 'MiniMax (Direct)',
    category: 'api_key',
    group: 'API Providers',
    order: 33,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
  {
    id: 'zai',
    ompId: 'zai',
    name: 'Z.AI (GLM)',
    category: 'api_key',
    group: 'API Providers',
    order: 34,
    selectable: true,
    finalClassification: 'UNCLASSIFIED',
  },
];
